id: 6a014818-9739-4a1b-995b-8f2a4e3d6f4f
name: Unique HCPs Between Two Datasets
description: cloned from 6cab67fc-ad4d-44f0-892c-9dc24b1340a7
accessibility: ACCOUNT
isNetworkRestricted: true
analyticDefinitionVersion:
  id: b0377adf-22e1-4f78-a7d0-cc123369fc8d
  version: 0.0.1
  description: cloned from 9f4a9b33-7278-4e7c-97c6-b1f73810fc6e
  type: Python
  publishingStatus: DRAFT
  contributorDefinedInputs:
    - name: table_1
      label: Table from Dataset Builder
      type: DATA_COLLECTION
      required: true
    - name: table_2
      label: Table from Dataset Builder
      type: DATA_COLLECTION
      required: true
  contributorDefinedOutputs:
    - name: UNIQUE_HCPS
  file_path: analytic.py
  requirements_path: requirements.txt
